import type {Grid,Layout,Mesh,Settings} from './types';
export interface Annotation {id:string;name:string;kind:'text'|'png';text:string;image?:string;threshold:number;invert:boolean;mask:number[];pixels_w:number;pixels_h:number;enabled:boolean;placement:'terrain'|'porch';treatment:'raised'|'engraved';x_mm:number;y_mm:number;width_mm:number;height_mm:number;angle_deg:number;depth_mm:number;porch_depth_mm:number;porch_align:'base'|'edge'}
export function xy(l:Layout,p:number[]):[number,number]{const u=(p[0]-l.bounds[0])/(l.bounds[2]-l.bounds[0]),v=(p[1]-l.bounds[1])/(l.bounds[3]-l.bounds[1]);return l.rotated?[(1-v)*l.width,u*l.depth]:[u*l.width,v*l.depth];}
export function surfaceZ(g:Grid,l:Layout,x:number,y:number){const u=l.rotated?y/l.depth:x/l.width,v=l.rotated?1-x/l.width:y/l.depth;const lon=l.bounds[0]+u*(l.bounds[2]-l.bounds[0]),lat=l.bounds[1]+v*(l.bounds[3]-l.bounds[1]);const gx=Math.max(0,Math.min(g.width-1,(lon-g.bounds[0])/(g.bounds[2]-g.bounds[0])*(g.width-1))),gy=Math.max(0,Math.min(g.height-1,(lat-g.bounds[1])/(g.bounds[3]-g.bounds[1])*(g.height-1)));const i=Math.min(g.width-2,Math.floor(gx)),j=Math.min(g.height-2,Math.floor(gy)),a=gx-i,b=gy-j;const z=g.elevations[j*g.width+i]*(1-a)*(1-b)+g.elevations[j*g.width+i+1]*a*(1-b)+g.elevations[(j+1)*g.width+i]*(1-a)*b+g.elevations[(j+1)*g.width+i+1]*a*b;return (z-l.minimum)*l.scale*l.height_factor+l.base_height;}
export function boundaryXY(s:Settings,l:Layout):[number,number][]{return s.boundary.length?s.boundary.map(p=>xy(l,p)):[[0,0],[l.width,0],[l.width,l.depth],[0,l.depth]];}
function inside(p:number[],poly:number[][]){let yes=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;}
export function snapPorch(a:Annotation,s:Settings,l:Layout){const poly=boundaryXY(s,l);let best=Infinity,found:any;const area=poly.reduce((v,p,i)=>{const q=poly[(i+1)%poly.length];return v+p[0]*q[1]-q[0]*p[1];},0);for(let i=0;i<poly.length;i++){const p=poly[i],q=poly[(i+1)%poly.length],dx=q[0]-p[0],dy=q[1]-p[1],len=Math.hypot(dx,dy);if(len<a.width_mm+7)continue;const margin=(a.width_mm+6)/2/len,t=Math.max(margin,Math.min(1-margin,((a.x_mm-p[0])*dx+(a.y_mm-p[1])*dy)/len**2)),x=p[0]+t*dx,y=p[1]+t*dy,d=Math.hypot(x-a.x_mm,y-a.y_mm);if(d<best){best=d;const sign=area>0?1:-1;found={x,y,ux:dx/len*sign,uy:dy/len*sign};}}if(!found)throw new Error('This porch needs a longer straight boundary edge. Reduce its width or use terrain placement.');return found;}
function prism(points:number[][],top:(x:number,y:number)=>number,bottom:(x:number,y:number)=>number):Mesh{const positions=[...points.flatMap(p=>[...p,top(p[0],p[1])]),...points.flatMap(p=>[...p,bottom(p[0],p[1])])];return {positions,indices:[0,1,2,0,2,3,6,5,4,7,6,4,0,4,5,0,5,1,1,5,6,1,6,2,2,6,7,2,7,3,3,7,4,3,4,0]};}
export function annotationGeometry(a:Annotation,g:Grid,s:Settings,l:Layout){if(![a.x_mm,a.y_mm,a.width_mm,a.height_mm,a.angle_deg,a.depth_mm,a.porch_depth_mm].every(Number.isFinite)||a.width_mm<=0||a.height_mm<=0||a.depth_mm<=0||a.depth_mm>10||a.pixels_w<1||a.pixels_h<1||a.pixels_w*a.pixels_h>32768||a.mask.length!==a.pixels_w*a.pixels_h)throw new Error('Invalid annotation dimensions or image.');const poly=boundaryXY(s,l);let cx=a.x_mm,cy=a.y_mm,angle=a.angle_deg*Math.PI/180,porch:Mesh|undefined,flat=0;let depth=Math.max(a.porch_depth_mm,a.height_mm+6);
 if(a.placement==='porch'){const edge=snapPorch(a,s,l);angle=Math.atan2(edge.uy,edge.ux);cx=edge.x+edge.uy*(depth/2-.5);cy=edge.y-edge.ux*(depth/2-.5);flat=a.porch_align==='edge'?Math.max(l.base_height,surfaceZ(g,l,edge.x,edge.y)):l.base_height;flat=Math.max(flat,a.depth_mm+.4);const w=a.width_mm+6;const pts=[[-w/2,-depth/2],[w/2,-depth/2],[w/2,depth/2],[-w/2,depth/2]].map(([x,y])=>[cx+x*Math.cos(angle)-y*Math.sin(angle),cy+x*Math.sin(angle)+y*Math.cos(angle)]);porch=prism(pts,()=>flat,()=>0);}
 const c=Math.cos(angle),sn=Math.sin(angle),point=(x:number,y:number)=>[cx+x*c-y*sn,cy+x*sn+y*c];const z=(x:number,y:number)=>porch?flat:surfaceZ(g,l,x,y);const solids:Mesh[]=[],preview:Mesh[]=[];const dx=a.width_mm/a.pixels_w,dy=a.height_mm/a.pixels_h;
 for(let row=0;row<a.pixels_h;row++)for(let col=0;col<a.pixels_w;){if(!a.mask[row*a.pixels_w+col]){col++;continue;}let end=col+1;while(end<a.pixels_w&&a.mask[row*a.pixels_w+end])end++;const segments=Math.max(1,Math.ceil((end-col)*dx/1));for(let k=0;k<segments;k++){const left=-a.width_mm/2+(col+(end-col)*k/segments)*dx,right=-a.width_mm/2+(col+(end-col)*(k+1)/segments)*dx,lo=a.height_mm/2-(row+1)*dy,hi=lo+dy;const points=[[left-.0002,lo-.0002],[right+.0002,lo-.0002],[right+.0002,hi+.0002],[left-.0002,hi+.0002]].map(([x,y])=>point(x,y));if(!porch&&points.some(p=>!inside(p,poly)))throw new Error('Move the annotation fully inside the terrain, or choose an attached porch.');const raised=a.treatment==='raised';const floor=(x:number,y:number)=>Math.max(.4,z(x,y)-a.depth_mm);solids.push(prism(points,raised?(x,y)=>z(x,y)+a.depth_mm:(x,y)=>z(x,y)+2,raised?()=>.3:floor));preview.push(prism(points,raised?(x,y)=>z(x,y)+a.depth_mm:(x,y)=>floor(x,y)+.002,raised?z:(x,y)=>floor(x,y)-.005));}col=end;}
 if(!solids.length)throw new Error('The annotation is empty. Adjust its text, threshold, or selected colors.');return {solids,preview,porch,center:[cx,cy,z(cx,cy)] as [number,number,number],angle,depth};}
export function combineMeshes(meshes:Mesh[]):Mesh{const positions:number[]=[],indices:number[]=[];for(const m of meshes){const n=positions.length/3;positions.push(...m.positions);indices.push(...Array.from(m.indices,i=>i+n));}return {positions,indices};}
