import {topoSurface} from './topo';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import type {Mesh,Layout,Overlay,Feature,Asset} from './types';
export const colors={trail:0xe78a43,road:0xc2b17a,stream:0x609ca7};
export class Viewer{
 renderer:THREE.WebGLRenderer;scene=new THREE.Scene();camera:THREE.PerspectiveCamera;controls:OrbitControls;
 model=new THREE.Group();land=new THREE.Group();features=new THREE.Group();frame=new THREE.Group();private surface?:THREE.Mesh;layout?:Layout;
 onNorthAngle?:(angle:number)=>void;onTopoStatus?:(text:string)=>void;
 private topo?:THREE.Mesh;private topoEnabled=true;private topoKey='';private topoRequest=0;
 private featureCarveMask?:ImageData;
 private carveCanvas=document.createElement('canvas');private carveTexture:THREE.CanvasTexture;private carveSize=new THREE.Vector2(1,1);
 private overlays=new Map<string,THREE.Object3D[]>();private wire=false;private contours=true;private clip=new THREE.Plane(new THREE.Vector3(0,-1,0),10000);private review=false;private dirty=true;
 private ray=new THREE.Raycaster();private pointer=new THREE.Vector2();onPick?:(id:string)=>void;onBoundary?:(p:[number,number])=>void;
 private boundaryLine?:THREE.Line;private dragging=false;private down=[0,0];
 constructor(private host:HTMLElement){this.carveCanvas.width=this.carveCanvas.height=2048;this.carveTexture=new THREE.CanvasTexture(this.carveCanvas);this.carveTexture.minFilter=THREE.LinearFilter;this.carveTexture.generateMipmaps=false;this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setClearColor(0xe9ede6);const gl=this.renderer.getContext();const dbg=gl.getExtension("WEBGL_debug_renderer_info");const software=dbg&&/SwiftShader|llvmpipe/i.test(gl.getParameter(dbg.UNMASKED_RENDERER_WEBGL));this.renderer.shadowMap.enabled=!software;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.2;this.renderer.localClippingEnabled=true;host.append(this.renderer.domElement);
 this.camera=new THREE.PerspectiveCamera(35,1,.1,4000);this.camera.up.set(0,0,1);this.camera.position.set(260,-340,310);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.dampingFactor=.08;this.controls.minDistance=30;this.controls.maxDistance=1400;this.controls.maxPolarAngle=Math.PI*.49;
 this.scene.add(new THREE.HemisphereLight(0xffffff,0x485146,2));const sun=new THREE.DirectionalLight(0xfff4df,3.4);sun.position.set(-140,-180,400);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-350;sun.shadow.camera.right=350;sun.shadow.camera.top=350;sun.shadow.camera.bottom=-350;sun.shadow.normalBias=.15;this.scene.add(sun);
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(2500,2500),new THREE.MeshStandardMaterial({color:0xe9ede6,roughness:1}));floor.position.z=-.7;floor.receiveShadow=true;this.scene.add(floor);const grid=new THREE.GridHelper(1000,100,0xc3cec2,0xd7dfd4);grid.rotation.x=Math.PI/2;grid.position.z=-.5;(grid.material as THREE.Material).transparent=true;(grid.material as THREE.Material).opacity=.55;grid.visible=false;
 this.scene.add(this.model);this.model.add(this.land,this.features,this.frame);
 new ResizeObserver(()=>this.resize()).observe(host);this.resize();this.controls.addEventListener("change",()=>{this.dirty=true});this.renderer.setAnimationLoop(()=>{this.controls.update();if(this.dirty){this.updateNorth();this.dirty=false;this.renderer.render(this.scene,this.camera);}});
 host.addEventListener('pointerdown',e=>{this.down=[e.clientX,e.clientY];this.dragging=false});host.addEventListener('pointermove',e=>{if(Math.hypot(e.clientX-this.down[0],e.clientY-this.down[1])>4)this.dragging=true;});
 host.addEventListener('click',e=>{if(this.dragging)return;const r=this.renderer.domElement.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.ray.setFromCamera(this.pointer,this.camera);if(this.onBoundary&&this.surface){const hit=this.ray.intersectObject(this.surface)[0];if(hit){const p=this.model.worldToLocal(hit.point.clone());this.onBoundary([p.x,p.y]);}return;}const hits=this.ray.intersectObjects(this.features.children,true);const hit=hits.find(h=>h.object.visible);if(hit?.object.userData.id)this.onPick?.(hit.object.userData.id);});}
 invalidate(){this.dirty=true;}
 resize(){this.dirty=true;const w=this.host.clientWidth,h=this.host.clientHeight;this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 geometry(m:Mesh){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(m.positions,3));g.setIndex(new THREE.BufferAttribute(new Uint32Array(m.indices),1));g.computeVertexNormals();return g;}
 private clear(g:THREE.Group){g.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Line){o.geometry.dispose();const materials=Array.isArray(o.material)?o.material:[o.material];materials.forEach(m=>m.dispose())}});g.clear();}
 private terrainMaterial(){const m=new THREE.MeshStandardMaterial({color:0x819981,roughness:.92,metalness:0,wireframe:this.wire,clippingPlanes:[this.clip]});m.onBeforeCompile=shader=>{shader.uniforms.showContours={value:this.contours?1:0};shader.uniforms.carveMask={value:this.carveTexture};shader.uniforms.carveSize={value:this.carveSize};shader.vertexShader='varying vec3 vTerrain; varying float vTop;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nvTerrain = position;vTop=normal.z;');shader.fragmentShader='varying vec3 vTerrain; varying float vTop; uniform sampler2D carveMask; uniform vec2 carveSize; uniform float showContours;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>
 if(vTop>0.01 && texture2D(carveMask,vTerrain.xy/carveSize).r>0.5)discard;
 float h = clamp(vTerrain.z / 50.0, 0.0, 1.0);
 diffuseColor.rgb *= mix(vec3(0.55,0.72,0.62),vec3(1.19,1.18,0.90),h);
 float level = vTerrain.z / 1.0; float fw=max(fwidth(level),0.003);
 float contour=1.0-smoothstep(0.0,fw*1.05,abs(fract(level+0.5)-0.5));
 diffuseColor.rgb=mix(diffuseColor.rgb,vec3(0.22,0.34,0.27),contour*0.26*showContours);`);m.userData.shader=shader;};return m;}
 setTerrain(mesh:Mesh,layout:Layout,fit=false){this.dirty=true;this.review=false;this.layout=layout;this.carveSize.set(layout.width,layout.depth);this.carveCanvas.getContext('2d')!.clearRect(0,0,2048,2048);this.carveTexture.needsUpdate=true;this.clear(this.land);this.model.position.set(-layout.width/2,-layout.depth/2,0);const surface=new THREE.Mesh(this.geometry(mesh),this.terrainMaterial());surface.castShadow=true;surface.receiveShadow=true;this.land.add(surface);this.surface=surface;void this.loadTopo();if(fit)this.fit();}
 // Preview ribbons retain their original 0.35 mm protrusion; tiny class offsets avoid crossing flicker.
 setOverlays(overlays:Overlay[],features:Feature[]){this.dirty=true;this.clear(this.features);this.overlays.clear();const enabled=new Map(features.map(f=>[f.id,f.enabled&&f.treatment!=='hide']));const ctx=this.carveCanvas.getContext('2d')!;ctx.clearRect(0,0,2048,2048);ctx.fillStyle='white';
 for(const o of overlays){const id=o.id.slice(0,o.id.lastIndexOf('#'));const carve=o.treatment==='v_carve';const material=new THREE.MeshStandardMaterial({color:carve?0x60755e:colors[o.class],roughness:.85,clippingPlanes:[this.clip],polygonOffset:!carve,polygonOffsetFactor:o.class==='trail'?-3:o.class==='road'?-2:-1,polygonOffsetUnits:-2});const mesh=new THREE.Mesh(this.geometry(o.mesh),material);mesh.userData.id=id;mesh.userData.carve=carve;if(carve){mesh.userData.rawFloor=Array.from(o.mesh.positions);const attr=mesh.geometry.getAttribute('position');for(let i=0;i<attr.count;i++)attr.setZ(i,Math.max(.4,attr.getZ(i)));attr.needsUpdate=true;mesh.geometry.computeVertexNormals();}mesh.renderOrder=carve?4:o.class==='trail'?3:o.class==='road'?2:1;mesh.position.z=carve?0:o.class==='trail'?.009:o.class==='road'?.006:.003;mesh.visible=enabled.get(id)??true;this.features.add(mesh);this.overlays.set(id,[...(this.overlays.get(id)||[]),mesh]);
 if(carve&&mesh.visible&&this.layout){ctx.beginPath();for(let i=0;i<o.mesh.indices.length;i+=3){for(let k=0;k<3;k++){const j=o.mesh.indices[i+k]*3;const x=o.mesh.positions[j]/this.layout.width*2048,y=(1-o.mesh.positions[j+1]/this.layout.depth)*2048;if(k===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.closePath();}ctx.fill();}
 }this.featureCarveMask=ctx.getImageData(0,0,2048,2048);this.carveTexture.needsUpdate=true;}
 annotationMaterial(){return this.terrainMaterial();}
 annotationCuts(meshes:Mesh[]){const ctx=this.carveCanvas.getContext('2d')!;ctx.clearRect(0,0,2048,2048);if(this.featureCarveMask)ctx.putImageData(this.featureCarveMask,0,0);if(this.layout){ctx.fillStyle='white';for(const m of meshes){ctx.beginPath();for(let i=0;i<m.indices.length;i+=3){for(let k=0;k<3;k++){const j=m.indices[i+k]*3;const x=m.positions[j]/this.layout.width*2048,y=(1-m.positions[j+1]/this.layout.depth)*2048;if(k===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.closePath();}ctx.fill();}}this.carveTexture.needsUpdate=true;this.dirty=true;}
 setBaseHeight(delta:number){this.dirty=true;for(const group of [this.land,this.features])for(const child of group.children){if(child instanceof THREE.Mesh){const attr=child.geometry.getAttribute('position');for(let i=0;i<attr.count;i++){if(child.userData.carve){child.userData.rawFloor[i*3+2]+=delta;attr.setZ(i,Math.max(.4,child.userData.rawFloor[i*3+2]));}else if(attr.getZ(i)>0)attr.setZ(i,attr.getZ(i)+delta);}attr.needsUpdate=true;child.geometry.computeBoundingSphere();child.geometry.computeBoundingBox();}}}
 toggle(id:string,enabled:boolean){this.dirty=true;this.overlays.get(id)?.forEach(o=>o.visible=enabled);}
 highlight(id:string|null){this.dirty=true;for(const [key,objects] of this.overlays){for(const o of objects){if(o instanceof THREE.Mesh){o.material.emissive?.setHex(key===id?0x5d310b:0);o.material.emissiveIntensity=key===id?.5:0;}}}}
 showAsset(asset:Asset,layout:Layout){this.dirty=true;this.setTerrain(asset.terrain,layout);this.review=true;this.clear(this.features);this.overlays.clear();for(const p of asset.inserts){const m=new THREE.Mesh(this.geometry(p.mesh),new THREE.MeshStandardMaterial({color:colors[p.class as keyof typeof colors],roughness:.65,clippingPlanes:[this.clip]}));m.position.fromArray(p.origin);m.userData.origin=p.origin;m.userData.id=p.id;m.castShadow=true;this.features.add(m);}}
 explode(value:number){this.dirty=true;if(!this.review)return;this.features.children.forEach(o=>{const origin=o.userData.origin;if(origin)o.position.set(origin[0],origin[1],origin[2]+value)});}
 setSection(value:number){this.dirty=true;this.clip.constant=this.layout?this.layout.depth*(value/100)-this.layout.depth/2:10000;}
 setWire(value:boolean){this.dirty=true;this.wire=value;if(this.surface)(this.surface.material as THREE.MeshStandardMaterial).wireframe=value;}
 previewHeight(scale:number){this.model.scale.z=scale;this.dirty=true;}
 setContours(value:boolean){this.dirty=true;this.contours=value;const material=this.surface?.material as THREE.MeshStandardMaterial|undefined;if(material?.userData.shader)material.userData.shader.uniforms.showContours.value=value?1:0;}
 fit(){this.dirty=true;const size=Math.max(this.layout?.width||220,this.layout?.depth||200);this.controls.target.set(0,0,12);// Look southwest from the lower northeast side of Post Canyon, independent of print-bed rotation.
 const east=size*1.65,north=size*.9;this.camera.position.set(this.layout?.rotated?-north:east,this.layout?.rotated?east:north,12+size*1.3);this.controls.update();}
 private updateNorth(){if(!this.layout)return;const center=new THREE.Vector3(0,0,10).project(this.camera);const north=new THREE.Vector3(this.layout.rotated?-10:0,this.layout.rotated?0:10,10).project(this.camera);const dx=(north.x-center.x)*this.host.clientWidth,dy=-(north.y-center.y)*this.host.clientHeight;this.onNorthAngle?.(Math.atan2(dx,-dy));}
 north(){const direction=new THREE.Vector3(this.layout?.rotated?-1:0,this.layout?.rotated?0:1,0);const radius=this.camera.position.distanceTo(this.controls.target);const polar=this.controls.getPolarAngle();this.camera.position.copy(this.controls.target).addScaledVector(direction,-radius*Math.sin(polar));this.camera.position.z=this.controls.target.z+radius*Math.cos(polar);this.controls.update();this.dirty=true;}
 setTopo(enabled:boolean){this.topoEnabled=enabled;if(this.topo)this.topo.visible=enabled;this.dirty=true;if(enabled)void this.loadTopo();}
 private async loadTopo(){if(!this.layout||!this.topoEnabled)return;const key=JSON.stringify(this.layout.bounds)+this.layout.width+','+this.layout.depth+','+this.layout.rotated;if(key===this.topoKey)return;this.topoKey=key;const request=++this.topoRequest;this.onTopoStatus?.('Loading topo map…');try{const data=await topoSurface(this.layout);if(request!==this.topoRequest)return;if(this.topo){this.scene.remove(this.topo);this.topo.geometry.dispose();const m=this.topo.material as THREE.MeshBasicMaterial;m.map?.dispose();m.dispose();}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(data.corners.flatMap(p=>[p[0],p[1],-.4]),3));g.setAttribute('uv',new THREE.Float32BufferAttribute([0,0,1,0,1,1,0,1],2));g.setIndex([0,1,2,0,2,3]);const texture=new THREE.CanvasTexture(data.canvas);texture.colorSpace=THREE.SRGBColorSpace;this.topo=new THREE.Mesh(g,new THREE.MeshBasicMaterial({map:texture,side:THREE.DoubleSide}));this.topo.visible=this.topoEnabled;this.scene.add(this.topo);this.onTopoStatus?.(data.attribution);this.dirty=true;}catch(e){if(request===this.topoRequest){this.topoKey='';this.onTopoStatus?.((e as Error).message);}}}
 top(){this.dirty=true;const size=Math.max(this.layout?.width||220,this.layout?.depth||200);this.controls.target.set(0,0,0);this.camera.position.set(this.layout?.rotated?.01:0,this.layout?.rotated?0:-.01,size*2);this.controls.update();}
 boundary(points:[number,number][]){this.dirty=true;if(this.boundaryLine){this.frame.remove(this.boundaryLine);this.boundaryLine.geometry.dispose();}if(!points.length)return;const data=points.map(p=>new THREE.Vector3(p[0],p[1],70));const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(data),new THREE.LineBasicMaterial({color:0xe88945,depthTest:false}));line.renderOrder=100;this.frame.add(line);this.boundaryLine=line;}
}

